name: smartseq2env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - star=2.7.1a
  - rsem=1.3.1
  - fastqc=0.11.8
  - multiqc=1.7
  - subread=1.6.3
  - docopt
  - pandas
  - samtools